#!/usr/bin/env python3
"""
Create simple placeholder icons without PIL dependency
"""
import os
import base64

# Simple 1x1 pixel PNG in base64 (transparent)
TRANSPARENT_PNG = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChAI9jM8lTgAAAABJRU5ErkJggg=="

# Simple colored PNG data for hotel icon
HOTEL_ICON_DATA = """
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAG+0lEQVR4nO3d3WsUZxzG8WfmndndJJvNJtGYaKKJr1HwBREFwQu9sAW9sIUWetGL3vSm/Qf6D/RCL3rRG29aKLQFoS+0UFqwYFsQX6C+xJdEjdGYmGw2yWaz7+/szOzOzs7szs5k5/eDCWR3Ztdnfvv7PTNPZmYlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABApVnNb0paSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpaSStpJa2klbSSVtJKWkkraSWtpJW0klbSSlpJK2klraSVtJJW0kpakGBJUkrO78qd7xW8X/B6we8Hvl/g/UKu53l+J3e9x4rXy72e639J7ve+pP3F7xd+v9CzJb2u3OsF/k6w/yXdS9B1JT0bOKPwcwnLLLNIkt0EzxBrOh99tLm2k4nFSqyWWK1Ry1qdHb9qQkNTAwqabcfzjmX5g4yxNMfaQgOWsBzS9ryxNMfaQgO7UEaJf7/4a5fydwu+Xqz1y3m9SqqR9JaB12tGk6uFfD9BG2cBo3q1nv4lY6RhXJh8I/8O0d8vPLPS2d/mPHu8bUYBgA6zAAA6xDnOsQAAAEFJREFUeKD7e3NzG3fu/T+rTF6iuFKqrSlGqrG9jkuMnxjz6sTtgPKHy2Wq4cJyv179fhEADu67OGDnQEkY5eHOKBxpY7dX3i1NxnKBq9eNlS5mW7FEKBr7kJy7BT/zS9pTuHnx3zr/Kx3lGX8WBAAyDVkVQLtNhOiCtNtLoQCULhMsyClxhyQ9Kh8mLchMFshgFKgStcQ6w2gpDU1NbR28yHMHq4e99NhVWKDqGsL+PqIzHRdrlC7OsqKaLDsGGqcyEACE7JDQzLJC9n9h1ikUkFh86Vr9TLfNBiRn/U6kBvkKgAHEAKgF3CbCt9RDvLJjBdDuOhGzqcFZUVr8FqhvRnTrsJthQz6AOMAaDNJ8A3JLBQKBAEBxnKJMJjnWKJjQrD6EsUfBUGBMINEgX6Ux1q8F8wHFADgSwb6FWpBpzKNiMOJuGVrQ7Jm9rHgVjsJtPOmG+sIqE4t0yOBNT3T35qRf9t7g50U6LuIeFfOI2hHqJsLHEBgPQFq8v8JBz9CfF5dKHWWLxBGGP+Xt1mSfKECUjgFPBZJg2l4q9T4MFsKCl6JrSySpUlbKIJBJnD7FLiGmJbA6h/wLgKmGgk4Y2YCc8ZGBnRnchUlnlJm8HhgJu2xmFUCHaELbOJsUOEgKsxFUK2MUa2wEAiOgJApBbhAQQNF8xNjsUj5CU6NZ9Mki9JNxOAoKgFOuQFJ7c7qFVVBGOMCpBoI+8AhFm1dMdQ1OZkEHq7C7I8t1h3T2t9IkUcCgA1XqagGlMjrO9hJlZhpUEJdxMrQsn3WgmU8JjnCt9jhfyxgQDGp0B8X7OLiJDrKDrNPMnKAeOqEADJfGWuEKqfJqr5J7Ux4wKOVqpyh8tG9IG0cUGrVjdFBUPB8+nj5pF/E+2z9Ft3qW+O8C/vxYOhRf6iJnfKOhsZUWVb+vQUz1TxwrHWOH8cjgGBdCKqeBGJiJQWLKpnNfzVd+ZLi3o7KFvzFdz4qp4iOZTbJE1mBo1rUbOaC9S1w6RAa7b6lRgOJU3rjm4xb1eKZGTsqUNLLs4E4VLdlHgf6CbIdN1kKMW/7+LKs6/o4VNtNMlRs1s8xJcGKJGnuGqNa6sX6xGsQCoxO8CAPRkMjhkSHOlGhCUBjQr0MxUiQ6E1nBAMBqyTxpnWFBT2TzuTEMy9bfYHjFQghJACcI8J3qkGBv8dKlqg8KAEmX8vl0wk7MtpF6OcUJhvJhY9YlFpQjgCLVQDJACREEzxkjxC4yl3OQVo2RRIQcnT2zYN5rVOQ55Kw9eMh1MgTh4pS5e9ckAokPn3rEXLGLuW0LjHW3v7+gEKsFfx3LFZhCJSkgAAAAASUVORK5CYII=
"""

# Create icons directory if it doesn't exist  
icons_dir = "/mnt/c/Users/T14/Desktop/hotel_flask_app/static/icons"
os.makedirs(icons_dir, exist_ok=True)

# Icon sizes needed
sizes = [16, 32, 72, 96, 128, 144, 152, 192, 384, 512]

# Create a simple colored square for each size (placeholder)
for size in sizes:
    # For now, create empty files as placeholders
    filename = f"icon-{size}x{size}.png"
    filepath = os.path.join(icons_dir, filename)
    
    # Write a simple placeholder PNG (1x1 transparent pixel)
    with open(filepath, 'wb') as f:
        f.write(base64.b64decode(TRANSPARENT_PNG))
    
    print(f"Created placeholder {filename}")

print(f"\n✅ Placeholder PWA icons created in {icons_dir}")
print("Note: These are 1x1 transparent placeholders. Replace with actual hotel icons for production.")